language: node_js
node_js:
  - "12.13"

install:
  - npm ci
script:
  - npm run build-prod-min && npm run build-prod && npm run build-css
deploy:
  provider: npm
  email: "amalov@reinform-int.ru"
  api_key: "${NPM_API_KEY}"
